### PR TITLE
Feature/OIDC bitbucket

### PR DESCRIPTION
**Pull request by mahamed-ar**
oidc setup + role

### CODE REVIEW

**Comment by mahamed-ar** [comment]
test ✅
image

oidc setup ✅
image

bitbucket roles ✅
image

github roles ✅
image

bitbucket pipeline ✅
image

**Comment by gambol99** [comment]
cc @m13t …

**Comment by gambol99** [comment]
We could probably use https://registry.terraform.io/providers/zahiar/bitbucket/latest/docs/data-sources/bitbucket_repository within the terraform-aws-cloudaccess pipeline to make it more user friendly

**Comment by gambol99** [comment]
Forgot to say … the pipeline ensure the commit messages conform to https://github.com/conventional-changelog/commitlint/#what-is-commitlint …

**Review by gambol99 — APPROVED** [review]
LG

**Pull request merged**
